paragraphs_previewer.settings:
  type: config_object
  label: 'Paragraphs previewer settings'
  mapping:
    previewer_view_mode:
      type: string
      label: 'Previewer view mode'

field.widget.settings.paragraphs_previewer:
  type: field.widget.settings.paragraphs

field.widget.settings.entity_reference_paragraphs_previewer:
  type: field.widget.settings.entity_reference_paragraphs
