field.formatter.settings.svg_formatter:
  type: mapping
  label: SVG Formatter settings
  mapping:
    inline:
      type: boolean
      label: Inline
    sanitize:
      type: boolean
      label: Sanitize
    apply_dimensions:
      type: boolean
      label: Apply dimensions
    width:
      type: integer
      label: Width
    height:
      type: integer
      label: Height
    enable_alt:
      type: boolean
      label: Enable alt attribute
    alt_string:
      type: string
      label: String or token(s) used for alt text for the image
    enable_title:
      type: boolean
      label: Enable title attribute
    title_string:
      type: string
      label: String or token(s) used for the title of the image
