<?php
/**
 * @file
 * Installation file for miniOrange REST API Module.
 */
use Drupal\rest_api_authentication\MiniorangeAPIAuthfeedback;
use Drupal\rest_api_authentication\Utilities;

function rest_api_authentication_uninstall(){
  Utilities::restAPIAuthenticationFeedbackFunc();
}


function rest_api_authentication_install(){

  $config = \Drupal::configFactory()->getEditable('rest_api_authentication.settings');
  drupal_flush_all_caches();
  $config->set('miniorange_rest_api_license_page_visited', "False");
  $config->set('miniorange_basic_authentication_tried', "Did not Try");
  $config->set('miniorange_api_key_authentication_tried', "Did not Try");
  $config->set('miniorange_rest_api_authentication_uninstall_status',0);
  $config->set('miniorange_rest_api_installation_time_ref', time());
  $config->save();
}
