<?php

/**
 * @file publishing_options.module
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_entity_type_alter().
 */
function publishing_options_entity_type_alter(array &$entity_types) {
  if ($entity_definition = $entity_types['node_type']) {
    $entity_definition->setFormClass('add', 'Drupal\publishing_options\Form\PublishingOptionsNodeTypeForm');
    $entity_definition->setFormClass('edit', 'Drupal\publishing_options\Form\PublishingOptionsNodeTypeForm');
    $entity_definition->setFormClass('delete', 'Drupal\publishing_options\Form\PublishingOptionsNodeTypeDeleteConfirm');
  }

  if ($entity_definition = $entity_types['node']) {
    $entity_definition->setFormClass('default', 'Drupal\publishing_options\Form\PublishingOptionsNodeForm');
    $entity_definition->setFormClass('edit', 'Drupal\publishing_options\Form\PublishingOptionsNodeForm');
    $entity_definition->setFormClass('delete', 'Drupal\publishing_options\Form\PublishingOptionsNodeDeleteForm');
  }
}

/**
 * Implements hook_help().
 */
function publishing_options_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.publishing_options':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        // Not using markdown module until filter is fixed.
        // Throwing Error: Class 'Michelf\MarkdownExtra' not found
//        $filter_manager = \Drupal::service('plugin.manager.filter');
//        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
//        $filter = $filter_manager->createInstance('markdown', ['settings' => $settings]);
        // return $filter->process($text, 'en');
        return check_markup($text, 'markdown');
      }
  }
  return NULL;
}
