<?php

/**
 * @file
 * Light Gallery module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Holds hooks and general functionality.
 */

/**
 * Implements hook_help().
 */
function lightgallery_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.lightgallery':
      $output = file_get_contents(\Drupal::service('extension.list.module')->getPath('lightgallery') . '/README.md');
      return '<pre>' . $output . '</pre>';
  }
}

/**
 * Implements hook_theme().
 */
function lightgallery_theme() {
  return [
    'lightgallery' => [
      'variables' => ['items' => [], 'id' => NULL],
      'template' => 'lightgallery',
    ],
  ];
}
